import WorkspaceLayout from "@/components/workspace/workspace-layout";
import CustomBarChart from "@/components/charts/bar-chart";

const sampleData = [
  { month: "Jan", sales: 400 },
  { month: "Feb", sales: 300 },
  { month: "Mar", sales: 600 },
  { month: "Apr", sales: 800 },
];

export default function VisualizationsPage() {
  return (
    <WorkspaceLayout>
      <div className="mx-auto max-w-7xl">
        <h1 className="mb-2 text-3xl font-bold text-white">
          Visualizations
        </h1>

        <p className="mb-8 text-zinc-400">
          AI-powered visual analytics
        </p>

        <div className="rounded-2xl border border-purple-900/30 bg-black/20 p-6">
          <h2 className="mb-2 text-xl font-semibold text-white">
            Monthly Sales Trend
          </h2>

          <p className="mb-6 text-zinc-400">
            Sample visualization generated by Querva
          </p>

          <CustomBarChart
            data={sampleData}
            xKey="month"
            yKey="sales"
          />
        </div>
      </div>
    </WorkspaceLayout>
  );
}